{
 "title": "Constantinople2",
 "tags": [ "constantinople" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Validator", "query": { "query": "label_values(deployer_name)" } },
   { "name": "Region", "query": { "query": "label_values(deployer_region)" } }
  ]
 },
 "panels": [
  {
   "title": "State Sync",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sync Progress",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {}
     ]
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Views Per Second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "rate(engine_simplex_voter_state_current_view[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "View Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "1 / avg(irate(engine_simplex_voter_state_current_view[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Number of Transactions [1m]",
   "type": "timeseries",
   "description": "Average number of transactions in each validator's proposed blocks",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Current View",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "engine_simplex_voter_state_current_view",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Marshal Processed Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "engine_marshal_processed_height",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Block Building Duration (p50)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 116 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, rate(engine_application_build_duration_bucket[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Block Building Duration (p75)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 116 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.75, rate(engine_application_build_duration_bucket[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Block Building Duration (p99)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 116 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(engine_application_build_duration_bucket[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Block Verify Duration (p50)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, rate(engine_application_verify_duration_bucket[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Block Verify Duration (p75)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.75, rate(engine_application_verify_duration_bucket[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Block Verify Duration (p75)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(engine_application_verify_duration_bucket[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Erasure Encode Duration (p50)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 132 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, rate(engine_application_erasure_encode_duration_bucket[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Erasure Encode Duration (p75)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 132 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.75, rate(engine_application_erasure_encode_duration_bucket[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Erasure Encode Duration (p99)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 132 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(engine_application_erasure_encode_duration_bucket[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Erasure Decode Duration (p50)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 140 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, rate(engine_shards_erasure_decode_duration_bucket[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Erasure Decode Duration (p75)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 140 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.75, rate(engine_shards_erasure_decode_duration_bucket[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Erasure Decode Duration (p99)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 140 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(engine_shards_erasure_decode_duration_bucket[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pruned Forks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 148 },
     "targets": [
      {
       "expr": "engine_stateful_pruned_forks_total",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Networking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Inbound Bandwidth per Second",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "irate(runtime_inbound_bandwidth_total{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}[1m])",
       "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
      }
     ]
    },
    {
     "title": "Outbound Bandwidth per Second",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "irate(runtime_outbound_bandwidth_total{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}[1m])",
       "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
      }
     ]
    },
    {
     "title": "Peers",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 65 },
     "targets": [
      {
       "expr": "p2p_tracker_directory_tracked{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}",
       "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
      }
     ]
    },
    {
     "title": "Connected Peers",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 65 },
     "targets": [
      {
       "expr": "count by(deployer_name, deployer_ip) (p2p_tracker_directory_connected{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"})",
       "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
      }
     ]
    },
    {
     "title": "Peer Average Connection Age",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(avg by(peer) (clamp_min((time() * 1000 - p2p_tracker_directory_connected{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}) / 1000, 0)))",
       "legendFormat": "{{peer}}"
      }
     ]
    },
    {
     "title": "Dial Attempts",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 65 },
     "targets": [
      {
       "expr": "sum by(deployer_name, deployer_ip) (p2p_dialer_attempts_total{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"})",
       "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
      }
     ]
    },
    {
     "title": "Peers Blocked",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 74 },
     "targets": [
      {
       "expr": "p2p_tracker_directory_blocked_total{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}",
       "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Writes per Second",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 84 },
     "targets": [
      {
       "expr": "irate(node_disk_writes_completed_total{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}[1m])",
       "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
      }
     ]
    },
    {
     "title": "Disk Reads per Second",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 84 },
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}[1m])",
       "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
      }
     ]
    },
    {
     "title": "Cached Bytes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_Cached_bytes{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}",
       "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
      }
     ]
    },
    {
     "title": "Open Blobs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 84 },
     "targets": [
      { "expr": "runtime_open_blobs", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Running Tasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
     "targets": [
      { "expr": "runtime_tasks_running", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Total Spawned Tasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
     "targets": [
      { "expr": "runtime_tasks_spawned_total", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 378 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"} - node_memory_MemFree_bytes{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"} - node_memory_Buffers_bytes{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"} - node_memory_Cached_bytes{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}",
       "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 378 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{deployer_name=~\"$Validator\", deployer_region=~\"$Region\", mountpoint=\"/\"} - node_filesystem_free_bytes{deployer_name=~\"$Validator\", deployer_region=~\"$Region\", mountpoint=\"/\"}",
       "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{deployer_arch=\"arm64\"} | json"
    }
   ]
  },
  {
   "title": "Spammer Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{deployer_name=\"spammer\"}"
    }
   ]
  }
 ]
}